# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65da9444b7e8f0d26e4eb25f166557ad573cd5268d0e4525e09b8b39f3c6c2cc2b503c7b97b3db3928a24fa7b908e201885361d9861c5f6a3dfea6d518e1e736

test:
  secret_key_base: f29684d425d55bdb28972ff4cf3a8c4b14bc8b4878be801fdab413d452283292294a6574fcac280db3b56fdb01e9a729ba02cbb62a79651c253bc054885a723e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
